#!/bin/bash

# Check to see if Homebrew is installed, and install it if it is not
echo "Checking if Homebrew is installed..."
command -v brew >/dev/null 2>&1 || { echo >&2 "Installing Homebrew Now"; \
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; }

echo "Updating Homebrew..."

brew update
export PATH="/usr/local/bin:$PATH"

# Check to see if Node is installed, and install it if it is not
if which node > /dev/null
   then
       echo "node is installed, skipping..."
   else
      echo "installing node..."
      brew install node
   fi

mkdir -p ../Atomic/server/node_modules
npm install --prefix ../server <package>

mkdir -p ../client/node_modules
npm install --prefix ../client <package>
